name: App service Build and Deploy Python package to Azure Web App

on:
  [push]

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_WEBAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:
env:
  AZURE_WEBAPP_NAME: CEIS400TDv2 # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'         # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.7'                  # set this to the python version to use

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: python install
      run: |
        sudo apt install python
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Install dependencies
        run: pip install -r requirements.txt
    - name: Start up commands for first time run
        run: python manage.py makemigrations homepage
          python manage.py migrate homepage
          python manage.py makemigrations inventory
          python manage.py migrate inventory
          python manage.py makemigrations transactions
          python manage.py migrate transactions
          python manage.py makemigrations
          python manage.py migrate

    - name: Start Server
        run: python manage.py runserver
    - uses: actions/checkout@v1
    - name: Building web app
      uses: azure/appservice-build@v2-beta
    - name: Deploy web App using GH Action azure/webapps-deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  # For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples